// Generated by gencpp from file demo_server_client/add.msg
// DO NOT EDIT!


#ifndef DEMO_SERVER_CLIENT_MESSAGE_ADD_H
#define DEMO_SERVER_CLIENT_MESSAGE_ADD_H

#include <ros/service_traits.h>


#include <demo_server_client/addRequest.h>
#include <demo_server_client/addResponse.h>


namespace demo_server_client
{

struct add
{

typedef addRequest Request;
typedef addResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct add
} // namespace demo_server_client


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::demo_server_client::add > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::demo_server_client::add&) { return value(); }
};

template<>
struct DataType< ::demo_server_client::add > {
  static const char* value()
  {
    return "demo_server_client/add";
  }

  static const char* value(const ::demo_server_client::add&) { return value(); }
};


// service_traits::MD5Sum< ::demo_server_client::addRequest> should match
// service_traits::MD5Sum< ::demo_server_client::add >
template<>
struct MD5Sum< ::demo_server_client::addRequest>
{
  static const char* value()
  {
    return MD5Sum< ::demo_server_client::add >::value();
  }
  static const char* value(const ::demo_server_client::addRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::demo_server_client::addRequest> should match
// service_traits::DataType< ::demo_server_client::add >
template<>
struct DataType< ::demo_server_client::addRequest>
{
  static const char* value()
  {
    return DataType< ::demo_server_client::add >::value();
  }
  static const char* value(const ::demo_server_client::addRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::demo_server_client::addResponse> should match
// service_traits::MD5Sum< ::demo_server_client::add >
template<>
struct MD5Sum< ::demo_server_client::addResponse>
{
  static const char* value()
  {
    return MD5Sum< ::demo_server_client::add >::value();
  }
  static const char* value(const ::demo_server_client::addResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::demo_server_client::addResponse> should match
// service_traits::DataType< ::demo_server_client::add >
template<>
struct DataType< ::demo_server_client::addResponse>
{
  static const char* value()
  {
    return DataType< ::demo_server_client::add >::value();
  }
  static const char* value(const ::demo_server_client::addResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEMO_SERVER_CLIENT_MESSAGE_ADD_H
