/**:
    ros__parameters:
      video_device: "/dev/video0"
      framerate: 10.0
      io_method: "mmap"
      frame_id: "camera"
      pixel_format: "yuyv"  # support  yuyv / yuyv2rgb / raw_mjpeg / mjpeg2rgb  Only yuyv / rgb can be seen by human
      av_device_format: "YUV422P"
      image_width: 1280
      image_height: 720
      camera_name: "pc_camera"
      camera_info_url: "package://usb_cam/config/camera_info.yaml"
      brightness: -1
      contrast: -1
      saturation: -1
      sharpness: -1
      gain: -1
      auto_white_balance: false
      white_balance: 4000
      autoexposure: false
      exposure: 100
      autofocus: false
      focus: -1